//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Outfits = new HashSet<Outfit>();
            this.Outfits1 = new HashSet<Outfit>();
            this.Outfits2 = new HashSet<Outfit>();
            this.Outfits3 = new HashSet<Outfit>();
            this.Outfits4 = new HashSet<Outfit>();
            this.Outfits5 = new HashSet<Outfit>();
            this.Outfits6 = new HashSet<Outfit>();
            this.Outfits7 = new HashSet<Outfit>();
            this.Outfits8 = new HashSet<Outfit>();
            this.Outfits9 = new HashSet<Outfit>();
            this.Outfits10 = new HashSet<Outfit>();
            this.Outfits11 = new HashSet<Outfit>();
        }
    
        public int ArticleID { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public int ArticleTypeID { get; set; }
        public int ColorID { get; set; }
        public int SeasonID { get; set; }
        public int OccasionID { get; set; }
    
        public virtual ArticleType ArticleType { get; set; }
        public virtual Color Color { get; set; }
        public virtual Occasion Occasion { get; set; }
        public virtual Season Season { get; set; }
        public virtual ICollection<Outfit> Outfits { get; set; }
        public virtual ICollection<Outfit> Outfits1 { get; set; }
        public virtual ICollection<Outfit> Outfits2 { get; set; }
        public virtual ICollection<Outfit> Outfits3 { get; set; }
        public virtual ICollection<Outfit> Outfits4 { get; set; }
        public virtual ICollection<Outfit> Outfits5 { get; set; }
        public virtual ICollection<Outfit> Outfits6 { get; set; }
        public virtual ICollection<Outfit> Outfits7 { get; set; }
        public virtual ICollection<Outfit> Outfits8 { get; set; }
        public virtual ICollection<Outfit> Outfits9 { get; set; }
        public virtual ICollection<Outfit> Outfits10 { get; set; }
        public virtual ICollection<Outfit> Outfits11 { get; set; }
    }
}
