//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Outfit
    {
        public int OutfitID { get; set; }

        [Display(Name = "Top")]
        public int ArticleID1 { get; set; }
        [Display(Name = "Top 2")]
        public Nullable<int> ArticleID2 { get; set; }
        [Display(Name = "Bottom")]
        public Nullable<int> ArticleID3 { get; set; }
        [Display(Name = "Shoes")]
        public Nullable<int> ArticleID4 { get; set; }
        [Display(Name = "Accessory")]
        public Nullable<int> ArticleID5 { get; set; }
        [Display(Name = "Accessory 2")]
        public Nullable<int> ArticleID6 { get; set; }
        [Display(Name = "Accessory 3")]
        public Nullable<int> ArticleID7 { get; set; }
        public Nullable<int> ArticleID8 { get; set; }
        public Nullable<int> ArticleID9 { get; set; }
        public Nullable<int> ArticleID10 { get; set; }
        public Nullable<int> ArticleID11 { get; set; }
        public Nullable<int> ArticleID12 { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Article Article1 { get; set; }
        public virtual Article Article2 { get; set; }
        public virtual Article Article3 { get; set; }
        public virtual Article Article4 { get; set; }
        public virtual Article Article5 { get; set; }
        public virtual Article Article6 { get; set; }
        public virtual Article Article7 { get; set; }
        public virtual Article Article8 { get; set; }
        public virtual Article Article9 { get; set; }
        public virtual Article Article10 { get; set; }
        public virtual Article Article11 { get; set; }
    }
}
