//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVCProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WardrobeMVCEntities : DbContext
    {
        public WardrobeMVCEntities()
            : base("name=WardrobeMVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Article> Articles { get; set; }
        public DbSet<ArticleType> ArticleTypes { get; set; }
        public DbSet<Color> Colors { get; set; }
        public DbSet<Occasion> Occasions { get; set; }
        public DbSet<Outfit> Outfits { get; set; }
        public DbSet<Season> Seasons { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
